name: store

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-store}
      POSTGRES_USER: ${POSTGRES_USER:-store}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-store}
    volumes:
      - $VOLUME/postgres/store:/var/lib/postgresql/data
    ports:
      - 5432:5432

  account:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${POSTGRES_USER:-store}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-store}

  auth:
    build:
      context: ./auth-service
      dockerfile: Dockerfile

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080